name: "Ensemble"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 11 * * 2,3"

jobs:
  ensemble:
    runs-on: ubuntu-20.04
    if: github.repository == 'epiforecasts/covid19-forecast-hub-europe'
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev

    - name: Install R dependencies
      run: |
       install.packages(c("here", "vroom", "dplyr", "tibble", "lubridate", "remotes", "cNORM", "yaml"))
       remotes::install_github("reichlab/covidHubUtils")
       remotes::install_github("epiforecasts/EuroForecastHub")
      shell: Rscript {0}

    - name: Create ensembles
      run: Rscript 'code/ensemble/EuroCOVIDhub/create-weekly-ensemble.R'

    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - mean ensemble"
        git add --all
        git commit -m "Build ensemble"
        git pull --rebase
        git push
        echo "pushed to github"

    - name: Create issue about failure
      if: failure() && github.event_name != 'workflow_dispatch'
      uses: JasonEtco/create-an-issue@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/action-issue-template.md
