name: Zoltar upload

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive # zoltar upload relies on validations submodule

    - name: Python set up
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range
        architecture: 'x64'

    - name: Install requirements
      run: |
        pip3 install git+https://github.com/reichlab/zoltpy/
        pip3 install -r validation/requirements.txt

    - name: Zoltar upload
      run: python3 validation/upload_zoltar.py

      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        Z_USERNAME: ${{secrets.Z_USERNAME}}
        Z_PASSWORD: ${{secrets.Z_PASSWORD}}

    - name: Create issue about failure
      if: failure() && github.event_name != 'workflow_dispatch'
      uses: JasonEtco/create-an-issue@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/action-issue-template.md
